

- name: Install latest zsh
  apt:
    name: zsh
    state: latest
  become: true

- name: Set vagrant user shell to zsh
  user:
    name: vagrant
    shell: /usr/bin/zsh
  become: true

- name: Install oh my zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
