- name: Add git PPA
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: true
    state: present
  become: true

- name: Install latest git
  apt:
    name: git
    state: latest
  become: true
